name: GitBook Deploy

on:
  push:
    branches: [ master ]  # 监听 master 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 使用 Docker 编译 GitBook
        run: |
          # 使用包含完整依赖的 Docker 镜像
          # 生成 _book 目录（编译后的 HTML）
          docker run --rm -v $(pwd):/app -w /app node:10-slim sh -c "
            npm install -g gitbook-cli &&
            gitbook install &&
            cd docs &&
            gitbook build
          "

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_book  # 指定编译产物目录